name: Build Homebrew Bottles

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build bottles for (e.g., 0.1.0)'
        required: true
        type: string
      tag:
        description: 'Git tag for the release (e.g., v0.1.0)'
        required: true
        type: string

env:
  FORMULA_NAME: shore
  SOURCE_REPO: MoonKraken/shore

jobs:
  build-bottles:
    strategy:
      matrix:
        os:
          - macos-13      # Ventura
          - macos-14      # Sonoma (Apple Silicon)
          - macos-15      # Sequoia
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update formula URL and version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          TAG="${{ github.event.inputs.tag }}"
          
          # Update version in formula
          sed -i '' "s|url \".*\"|url \"https://github.com/${{ env.SOURCE_REPO }}/archive/refs/tags/${TAG}.tar.gz\"|" shore.rb
          
          # Download the tarball and calculate sha256
          curl -L -o /tmp/shore.tar.gz "https://github.com/${{ env.SOURCE_REPO }}/archive/refs/tags/${TAG}.tar.gz"
          SHA256=$(shasum -a 256 /tmp/shore.tar.gz | awk '{print $1}')
          
          # Update sha256 in formula
          sed -i '' "s|sha256 \".*\"|sha256 \"${SHA256}\"|" shore.rb
          
          cat shore.rb

      - name: Clean Homebrew cache
        run: |
          # Remove stale cached downloads to avoid SHA mismatch errors
          brew cleanup -s
          rm -rf $(brew --cache)

      - name: Setup tap
        run: |
          # Create tap directory structure
          mkdir -p $(brew --repository)/Library/Taps/moonkraken/homebrew-shore
          cp shore.rb $(brew --repository)/Library/Taps/moonkraken/homebrew-shore/

      - name: Install formula
        run: |
          brew install --build-bottle moonkraken/shore/shore

      - name: Build bottle
        run: |
          brew bottle --json --root-url=https://github.com/${{ env.SOURCE_REPO }}/releases/download/${{ github.event.inputs.tag }} moonkraken/shore/shore

      - name: Get bottle filename
        id: bottle-name
        run: |
          BOTTLE_FILE=$(ls *.bottle.tar.gz)
          echo "filename=$BOTTLE_FILE" >> $GITHUB_OUTPUT
          
          # Also get the OS-specific name for the release
          if [[ "${{ matrix.os }}" == "macos-13" ]]; then
            OS_NAME="ventura"
          elif [[ "${{ matrix.os }}" == "macos-14" ]]; then
            OS_NAME="sonoma"
          elif [[ "${{ matrix.os }}" == "macos-15" ]]; then
            OS_NAME="sequoia"
          fi
          echo "os_name=$OS_NAME" >> $GITHUB_OUTPUT

      - name: Upload bottle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bottle-${{ steps.bottle-name.outputs.os_name }}
          path: |
            *.bottle.tar.gz
            *.bottle.json

      - name: Upload bottle to source repo release
        uses: softprops/action-gh-release@v1
        with:
          repository: ${{ env.SOURCE_REPO }}
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            *.bottle.tar.gz
          token: ${{ secrets.SOURCE_REPO_TOKEN }}

  update-formula:
    needs: build-bottles
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4

      - name: Download all bottle artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: bottle-*
          merge-multiple: true

      - name: Update formula with bottle checksums
        run: |
          # Extract bottle information from JSON files
          BOTTLE_BLOCK="  bottle do\n    root_url \"https://github.com/${{ env.SOURCE_REPO }}/releases/download/${{ github.event.inputs.tag }}\"\n"
          
          for json_file in *.bottle.json; do
            if [ -f "$json_file" ]; then
              # Parse JSON to get OS and sha256
              OS=$(jq -r 'keys[0] as $formula | .[$formula].bottle.tags | keys[0]' "$json_file")
              SHA256=$(jq -r 'keys[0] as $formula | .[$formula].bottle.tags['\"$OS\"'].sha256' "$json_file")
              
              BOTTLE_BLOCK="${BOTTLE_BLOCK}    sha256 cellar: :any_skip_relocation, ${OS}: \"${SHA256}\"\n"
            fi
          done
          
          BOTTLE_BLOCK="${BOTTLE_BLOCK}  end\n"
          
          # Insert bottle block after the license line
          awk -v bottle="$BOTTLE_BLOCK" '
            /license/ {
              print
              print ""
              printf "%b", bottle
              next
            }
            { print }
          ' shore.rb > shore.rb.tmp
          
          mv shore.rb.tmp shore.rb
          
          cat shore.rb

      - name: Commit and push updated formula
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add shore.rb
          git commit -m "Add bottles for ${{ github.event.inputs.tag }}"
          git push

