name: Build and Publish Bottles

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag from source repo (e.g., v0.1.0)'
        required: true
        type: string

env:
  HOMEBREW_NO_INSTALL_FROM_API: 1

jobs:
  build-bottles:
    strategy:
      matrix:
        os:
          - macos-14      # Sonoma (Apple Silicon)
          - macos-15      # Sequoia
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update formula to use specified tag
        run: |
          TAG="${{ github.event.inputs.tag }}"
          
          # Update URL to point to the specified tag
          sed -i '' "s|url \".*\"|url \"https://github.com/MoonKraken/shore/archive/refs/tags/${TAG}.tar.gz\"|" shore.rb
          
          # Download and calculate sha256
          curl -L -o /tmp/source.tar.gz "https://github.com/MoonKraken/shore/archive/refs/tags/${TAG}.tar.gz"
          SHA256=$(shasum -a 256 /tmp/source.tar.gz | awk '{print $1}')
          
          # Update sha256
          sed -i '' "s|sha256 \".*\"|sha256 \"${SHA256}\"|" shore.rb
          
          echo "Updated formula:"
          cat shore.rb

      - name: Clean Homebrew cache
        run: |
          brew cleanup -s
          rm -rf "$(brew --cache)"

      - name: Debug - Show system info
        run: |
          echo "OS: $(sw_vers -productVersion)"
          echo "Architecture: $(uname -m)"
          echo "Homebrew version: $(brew --version)"
          echo "Ruby version: $(ruby --version)"
          echo "Formula content:"
          cat shore.rb

      - name: Build bottle using test-bot
        run: |
          brew test-bot --only-cleanup-before
          brew test-bot --only-setup
          brew test-bot --only-formulae --skip-recursive-dependents --root-url="https://github.com/MoonKraken/shore/releases/download/${{ github.event.inputs.tag }}" --only-json-tab shore
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload bottles as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bottles-${{ matrix.os }}
          path: '*.bottle.*'

  upload-bottles:
    needs: build-bottles
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4

      - name: Download all bottles
        uses: actions/download-artifact@v4
        with:
          pattern: bottles-*
          merge-multiple: true

      # this step is for diagnostic purposes only
      - name: List downloaded files
        run: |
          echo "Files in current directory:"
          ls -la
          echo ""
          echo "All files recursively:"
          find . -type f -ls
          echo ""
          echo "Bottle JSON contents:"
          cat *.bottle.json || echo "No bottle JSON files found"

      - name: Rename bottles to match expected format
        run: |
          # Rename bottles from shore--X.Y.Z.platform.bottle.N.tar.gz
          # to shore-X.Y.Z.platform.bottle.tar.gz (without rebuild suffix)
          for file in shore--*.bottle.*.tar.gz; do
            if [ -f "$file" ]; then
              # Remove the double dash and the rebuild number
              newname=$(echo "$file" | sed 's/shore--/shore-/' | sed 's/\.bottle\.[0-9]*\.tar\.gz/.bottle.tar.gz/')
              echo "Renaming: $file -> $newname"
              mv "$file" "$newname"
            fi
          done
          echo ""
          echo "Files after renaming:"
          ls -la *.bottle.tar.gz

      - name: Upload bottles to source repo release
        uses: softprops/action-gh-release@v2
        with:
          repository: MoonKraken/shore
          tag_name: ${{ github.event.inputs.tag }}
          files: '*.bottle*.tar.gz'
          token: ${{ secrets.SOURCE_REPO_TOKEN }}
          fail_on_unmatched_files: true

      - name: Update formula with bottle information
        run: |
          # Merge bottle JSON files
          if ls *.bottle.json 1> /dev/null 2>&1; then
            jq -s 'reduce .[] as $item ({}; . * $item)' *.bottle.json > merged.bottle.json
            
            echo "Merged bottle JSON:"
            cat merged.bottle.json
            
            # Build bottle block from JSON
            echo "  bottle do" > bottle_block.txt
            echo "    root_url \"https://github.com/MoonKraken/shore/releases/download/${{ github.event.inputs.tag }}\"" >> bottle_block.txt
            
            jq -r '.[] | .bottle.tags | to_entries[] | "    sha256 cellar: :any_skip_relocation, " + .key + ": \"" + .value.sha256 + "\""' merged.bottle.json >> bottle_block.txt
            
            echo "  end" >> bottle_block.txt
            
            echo "Generated bottle block:"
            cat bottle_block.txt
            
            # Insert bottle block after license line in formula
            awk '
              /license/ {
                print
                print ""
                while ((getline line < "bottle_block.txt") > 0) {
                  print line
                }
                next
              }
              { print }
            ' shore.rb > shore.rb.tmp
            
            mv shore.rb.tmp shore.rb
            
            echo "Updated formula:"
            cat shore.rb
          else
            echo "No bottle JSON files found!"
            exit 1
          fi

      - name: Commit and push updated formula
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add shore.rb
          git commit -m "Add bottles for ${{ github.event.inputs.tag }}"
          git push

